### ISSUE TITLE
USB_DataLog_Run script paths

### ISSUE THREAD

**Issue by bobu01** [STMicroelectronics/fp-sns-datalog2#1]
**Caution**
The Issues are strictly limited for the reporting of problem encountered with the software provided in this project.

**Describe the set-up**
Install the fp-sns-datalog2 repository on a linux system using git clone

**Describe the bug**
`Utilities/cli_example/USB_DataLog_Run.sh` won't run. The file has incorrect paths for command and config file.

**How To Reproduce the bug**
Change to the directory with the USB_DataLog_Run script.  
chmod 777 to make the script executable
Run the script in a terminal.
File not found errors result

**Additional context**
Target folder name is `./bin_linux`, not `./bin_unix`
The default config file has a lower-case name with an underscore

**Screenshots**

**Comment by pradolis** [comment]
Issue has been noted and confirmed. Will be fixed in v1.2.0
