### ISSUE TITLE
Does not run on STEVAL-STWINKT1B

### ISSUE THREAD

**Issue by bitmorse** [STMicroelectronics/fp-sns-datalog2#13]
**Setup**

 * STEVAL-STWINKT1B
 * CubeIDE 1.13.2

**Describe the bug**

Cloning the project and compiling the respective project (Projects/Applications/STM32L4R9ZI-STWIN) using CubeIDE works.
Flashing the project (ST Link V3) on to the board works, however the project does not appear to be running. 

- "dmesg" shows a "STM32 BOOTLOADER" attached instead of the HSD device
- LED not blinking
- No BLE service discoverable

Flashing the datalog1 firmware project using the same method also works and the firmware runs. dmesg shows the HSD device.

**How To Reproduce the bug**
1. Flash this repository's Projects/Applications/STM32L4R9ZI-STWIN project on a freshly bought STEVAL-STWINKT1B

**Comment by pradolis** [comment]
Hello @bitmorse 
STWIN board has  a double-bank flash. Can you check if you are flashing/running the firmware on the proper bank?
![image](https://github.com/STMicroelectronics/fp-sns-datalog2/assets/104888083/c959e5d7-c0d5-4e35-96d2-8aec962ab13c)
To flash the code using one of the compatible IDE and debuggers, you need to make sure that the active flash bank is the first one. You can do this using the STM32CubeProgrammer:
![image](https://github.com/STMicroelectronics/fp-sns-datalog2/assets/104888083/15692115-fa93-4ad2-ad47-ce474797277a)
This is the proper MCU setup. 
Check this and then let you know if it restarts working properly.

Similar procedure is described for STWIN.box and SensorTile.box PRO.
To avoid possible issue in future, we'll improve the related chapter in User Manual and Quick Start Guide also for STWIN.

**Comment by bitmorse** [comment]
That fixes it! It works perfectly now. Thanks a lot!
