### ISSUE TITLE
ISPU core is detected as unknown 

### ISSUE THREAD

**Issue by benx13** [STMicroelectronics/fp-sns-datalog2#14]
ISPU core is detected as unknown and UCF file fails to upload it just gets stuck at the upload cycle 
hardware:
STEVAL-STWINBX1
with ISPU: STEVAL-C34KAT2
firmaware: FP-SNS-DATALOG2_2.1.1
st ble sensor for iOS 

![IMG_3093](https://github.com/STMicroelectronics/fp-sns-datalog2/assets/32802278/62fac40d-7751-4b75-bd73-760361c82937)

**Comment by pradolis** [comment]
Hello @benx13 
we are working on DATALOG2 v2.2.0 release, planned for end of July.
I'll share the issue internally so to find the proper solution.

Best regards
Simone

**Comment by pradolis** [comment]
Hello @benx13 
v2.2.0 will partially update ISPU support only via USB through the HSDPython SDK provided together with FP-SNS-DATALOG2. Unfortunately, we have still not been able to solve the UCF upload for ISPU via the ST BLE Sensor.

We'll continue to work on fixing this issue in both ST BLE Sensor and FP-SNS-DATALOG2 future releases.

Best regards,
Simone
