### ISSUE TITLE
cli_example not working on RPI 4 Model B (32/64 bit Raspbian OS)

### ISSUE THREAD

**Issue by alejandrolabajos** [STMicroelectronics/fp-sns-datalog2#15]
Hello, 
I am trying to run the cli_example script using my Raspberry Pi 4 model B, but I am facing different issues depending on the OS installed in the RPI.

_Some details before define how to reproduce the errors._
- STEVAL-STWINBX1 Firmware: FP-SNS-Datalog2 v2.1.1. Boot using Release binary file provided.
- Device: Raspberry Pi 4 Model B 8GB with a fresh boot.
- STM board is listed correctly using lsusb on RPI4.
![rpi1_A](https://github.com/STMicroelectronics/fp-sns-datalog2/assets/175111274/7c4b45dd-691c-4e31-9fea-a84a61e70163)
- All utilities working fine on my host PC (Windows 11).

**Error using Raspberry Pi OS (bookworm) 32-bit or Raspberry Pi OS Legacy (Debian based) 32-bit.** 

Same error encountered with both 32-bit OS.

_My_ _configuration:_

![rpi1_B](https://github.com/STMicroelectronics/fp-sns-datalog2/assets/175111274/847a65bb-ea26-47b9-9768-3f62befc4322)
![rpi1_C](https://github.com/STMicroelectronics/fp-sns-datalog2/assets/175111274/bb6d5a84-0041-41e1-af92-60d8ef9e6946)

_Workflow:_

I followed the README_Linux instructions located in cli_example folder (/Utilities/cli_example), but instead of using files of Linux folders i've used the files located in /raspberryPi_setup and /bin_raspberryPi4_32.

![rpi2](https://github.com/STMicroelectronics/fp-sns-datalog2/assets/175111274/8f810bd7-c5ca-41fe-b489-ba900a891fcd)

_Error message received:_

![rpi3](https://github.com/STMicroelectronics/fp-sns-datalog2/assets/175111274/8285ee14-a9d2-4e72-a4fa-1e30a5e31e8c)

**Error using Raspberry Pi OS (bookworm) 64-bit.** 

This is also mentioned in the Issue #8 by the user @francus_dev, the workflow proposed by @pradolis is not working, I got the same issue.

_My configuration:_
![image](https://github.com/STMicroelectronics/fp-sns-datalog2/assets/175111274/e4e06cf3-5858-48fb-8dcd-46b142c715fb)

_Error message received:_

` ./cli_example: error while loading shared libraries: libhs_datalog_v2.so: wrong ELF class: ELFCLASS32 `

Any help will be appreciated, since i am not an expert and i didn't have this type of difficulties running it on my Windows host PC. 
Thanks.

**Comment by alejandrolabajos** [comment]
Marked as closed. 

**SOLVED:** Regarding the section "Error using Raspberry Pi OS (bookworm) 32-bit or Raspberry Pi OS Legacy (Debian based) 32-bit.", the problem appeared because I wasn't disconnecting the board before running setup.sh script located in /raspberryPi_setup. Executing the script with the board disconnected, and then connecting the board to RPI and running cli-example located in /bin_raspberryPi worked perfect.

**NOT SOLVED:** Regarding the section "Error using Raspberry Pi OS (bookworm) 64-bit." I did not found the cause for this issue.

**Comment by pradolis** [comment]
Hello @alejandrolabajos 
Thanks for your feedbacks. If I well understood, the issue that still persists is the one already shared in #8 .
Am I right?

Best regards
Simone

**Comment by alejandrolabajos** [comment]
Hi @pradolis 

You are totally right.

Thank you for your fast reply,
Alex
