### ISSUE TITLE
Is it possible to create a real-time application that uses the hsdlink python SDK?

### ISSUE THREAD

**Issue by nicolasj92** [STMicroelectronics/fp-sns-datalog2#2]
I want to build an application that uses the sensor data over usb in near-real time. E.g. always perform some operations on the data of the last second. Is this possible with the SDK? So far I can only see that the data is stored in .dat files and needs to be converted post-acqusition before it can be used.
I tried to dig through the GUI application code to find out how its handling the real time plotting but so far I don't fully understand whats going on there.

**Comment by pradolis** [comment]
As you said, data are streamed than saved as .dat. Data stream is in raw data from the sensors (i.e.: 3 axis accelerometer stream is composed by interleaved data of 16 bit).
The ready-to-use scripts will save data and then allow you to convert to enable you post processing them.

If you need to add some processing on the fly, have a look at the HSD_Controller and HSD_DeviceConfigPage classes available in st_hsdatalog/HSD_GUI.
The Controller allocate a thread for each sensor. The main loop of the thread reads data from the USB, converts the data from raw bytes into meaningful data (i.e.: from 16-bit based stream into g-force data in float) and send/notify the data to the graphical part.
The DeviceConfigPage handle the graphical part, where in our use case receives data from the controller and plot them.

For your use case you can act on the DeviceConfigPage by extending or modifying it. Data are there, so you can process them as you need
