### ISSUE TITLE
Does a scaling take place when retriving data from file?

### ISSUE THREAD

**Issue by smellit** [STMicroelectronics/fp-sns-datalog2#6]
I have recorded data to a SD card using the STWIN.box and I want to do more data analysis (e.g. filtering) on it.

The sensor I uses is "iis3dwb_acc", when I retrive the data using `HSDatalog.get_dataframe` it seems that the data are not the same as when they are plotted with `HSDatalog.plot` does a scaling take place? Do I have to uses `HSDatalog.get_data_and_timestamps` to get same data?

**Comment by pradolis** [comment]
Hello @smellit 
By default, data are multiplied by the sensitivity, a scalar value used to convert data from sensors from raw value to a meaningful one with the proper unit of measurement (i.e.: from raw int16 value to mg for iis3dwb)
Al the provided scripts accepts different parameters.
By using '-r', data are not scaled
