### ISSUE TITLE
Corrupted data in long measurements

### ISSUE THREAD

**Issue by nicolasj92** [STMicroelectronics/fp-sns-datalog2#7]
I don`t understand how this issue can be closed as **completed**. Yes the explanation is that there is some USB interference or something similar but why is all data from that moment on corrupted? This basically makes it impossible to take measurements for more than a few minutes. I would see it as a bug that the software cannot recover from a transmission problem that probably only lasts a few milliseconds.

https://github.com/STMicroelectronics/fp-sns-datalog2/issues/3

_Originally posted by @nicolasj92 in https://github.com/STMicroelectronics/fp-sns-datalog2/issues/3#issuecomment-1706522534_

**Comment by pradolis** [comment]
Hello @nicolasj92 
Can you have a look and test the v2.1.0 just released (if you are still interested in our product)?
We worked also on USB communication side
A feedback from you can help us for further developments.

Best regards

**Comment by nicolasj92** [comment]
Hello @pradolis, we will do another trial next week and I will then include the sensor again and report here how it went.
Best regards

**Comment by pradolis** [comment]
Hello @nicolasj92 
No more feed on the topic, so let me close the issue.
v2.2.0 will be soon available.
If you are still interested in FP-SNS-DATALOG2 and you'd like to test it, feel free to comment and reopen the issue if needed.

Best regards
Simone
